#!/bin/bash

# comic-sharp-3
# Script to launch pyVid2 with a detailed cartoon post-processing effect

numArgs="${#@}"

# Path to playable media
if [[ $numArgs -eq 0 ]]; then
	mediaPath='../assets/video/'
else
	mediaPath="$1"
fi

../pyv2 --enableFFprobe --loopDelay=2 --playSpeed=1.5 --disableGIF --usePygameAudio\
	--comic-sharp --comic-sharp-amount 0.5 --color-quant 10 \
	--edge-low 30 --bilateral-d 3 \
	--Paths "${mediaPath}"
