#!/bin/bash

SUM=0
OVERALL=0
for DIR in /proc/[0-9]*; do
    PID=$(basename "$DIR")
    PROGNAME=$(ps -p "$PID" -o comm=)
    for SWAP in $(grep VmSwap "$DIR/status" 2>/dev/null | awk '{ print $2 }'); do
        SUM=$((SUM + SWAP))
    done
    if (( SUM > 0 )); then
        echo "PID=$PID swapped ${SUM} KB ($PROGNAME)"
    fi
    OVERALL=$((OVERALL + SUM))
    SUM=0
done
echo "Overall swap used: ${OVERALL} KB"

